// src/components/Footer.tsx
import React from "react";
import {Button} from "@/components/ui/button";
import {EnvelopeClosedIcon, GitHubLogoIcon, LinkedInLogoIcon, TwitterLogoIcon} from '@radix-ui/react-icons'

export const Footer: React.FC = () => (
  <div className={'flex w-full justify-evenly text-gray-500'}>
    <div>
      <Button variant={'ghost'} asChild>
        <a
          href={'https://youtu.be/UF8uR6Z6KLc'}
          target={'_blank'}
        >
          Stay hungry, stay foolish 🔥
        </a>
      </Button>
    </div>
    <div>
      <Button variant={'ghost'} asChild>
        <a
          href={'https://www.linkedin.com/in/maximilian-bethke-8521a918b/'}
          target={'_blank'}
        >
          <LinkedInLogoIcon/>
        </a>
      </Button>
      <Button variant={'ghost'} asChild>
        <a
          href={'https://twitter.com/maxbethke_'}
          target={'_blank'}
        >
          <TwitterLogoIcon/>
        </a>
      </Button>
      <Button variant={'ghost'} asChild>
        <a
          href={'https://github.com/maxbethke'}
          target={'_blank'}
        >
          <GitHubLogoIcon/>
        </a>
      </Button>
      <Button variant={'ghost'} asChild>
        <a
          href={'mailto:office@maxbethke.de'}
        >
          <EnvelopeClosedIcon/>
        </a>
      </Button>
    </div>
  </div>
)

// src/components/FooterComponent.vue
<template>
  <v-container class="footer" fluid>
    <div class="footer__section">
      <v-btn
        text
        href="https://youtu.be/UF8uR6Z6KLc"
      >
        Stay hungry, stay foolish <span class="icon">🔥</span>
      </v-btn>
    </div>
    <div class="footer__copyright"> 2022 Maximilian Bethke</div>
    <div class="footer__social-media">
      <v-btn icon href="https://www.linkedin.com/in/maximilian-bethke-8521a918b/">
        <v-icon>mdi-linkedin</v-icon>
      </v-btn>
      <v-btn icon href="https://twitter.com/maxbethke_">
        <v-icon>mdi-twitter</v-icon>
      </v-btn>
      <v-btn icon href="https://github.com/maxbethke">
        <v-icon>mdi-github</v-icon>
      </v-btn>
      <v-btn icon href="mailto://office@maxbethke.de">
        <v-icon>mdi-email</v-icon>
      </v-btn>
    </div>
  </v-container>
</template>

<script>
export default {
  name: "FooterComponent",
}
</script>

<style lang="sass" scoped>
.footer
  display: flex
  align-items: center
  justify-content: space-evenly
  color: rgba(0, 0, 0, .54)
  .icon
    color: rgb(0, 0, 0)
  &__copyright::before
    content: '\00A9'
</style>
